# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "bunnies", :force => true do |t|
    t.column "username",                  :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "secret",                    :string
    t.column "secret_confirmed_at",       :datetime
  end

  create_table "valentines", :force => true do |t|
    t.column "sender_id",    :integer
    t.column "recipient_id", :integer
    t.column "message",      :text
    t.column "created_at",   :datetime
  end

end
